version: '3.7'

services:
  pentagram:
    image: ghcr.io/ece4410j-pentagram/pentagram-backend
    env_file:
      - secret.env
    ports:
      - 18000:8000
  redis:
    image: redis:7.2-rc2
    restart: always
    command: redis-server
  postgres:
    image: postgres
    restart: always
    env_file:
      - secret.env
    ports:
      - 5432:5432
